# configs/app.yaml

# Application Configuration for Mafia Wars: Criminal Empire

# Environment (development, staging, production)
environment: development

# Server settings
server:
  port: 8000
  timeout_read: 30      # 30 seconds for reading request body
  timeout_write: 43200  # 12 hours for writing responses (for SSE)
  timeout_idle: 43200   # 12 hours for idle connections (for SSE)
  timeout_shutdown: 30  # 30 seconds for graceful shutdown

# Database settings
database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: mwce
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100

# JWT settings
jwt:
  secret: "your-secret-key-change-this-in-production" # Change this in production!
  token_lifetime: 168h # 7 days
