# configs/app.yaml

# Application Configuration for Mafia Wars: Criminal Empire

# Environment (development, staging, production)
environment: development

# Server settings
server:
  port: 8000
  timeout_read: 30      # 30 seconds for reading request body
  timeout_write: 43200  # 12 hours for writing responses (for SSE)
  timeout_idle: 43200   # 12 hours for idle connections (for SSE)
  timeout_shutdown: 30  # 30 seconds for graceful shutdown

# Database settings
database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: mwce
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100

# JWT settings
jwt:
  secret: "your-secret-key-change-this-in-production" # Change this in production!
  token_lifetime: 168h # 7 days

# Game settings
game:
  mechanics_file: "./configs/mechanics.yaml"
  territory_structure_file: "./configs/territory.yaml"
  operations_file: "./configs/operations.yaml"
  daily_operations_count: 10
  special_operations_count: 5
  operations_refresh_interval: 60 # in minutes
  market_price_update_interval: 60 # in minutes
  resource_limit:
    initial_crew: 500 # Default value: 5
    initial_weapons: 300 # Default value: 3
    initial_vehicles: 1000 # Default value: 1
    initial_money: 100000 # Default value: 10000
    max_crew: 2500 # Default value: 25
    max_weapons: 3000 # Default value: 30
    max_vehicles: 1200 # Default value: 12