campaigns:
- id: 88ab1cdf-645a-4a78-9a6c-2d75bfb2b93f
  name: The Family Business
  description: Establish your criminal empire in the city by taking over key territories
    and eliminating rivals.
  image_url: /assets/campaigns/family-business.jpg
  is_active: true
  chapters:
  - id: 9456da1e-7c32-4eb8-8cdf-3422c5fba8e1
    name: Starting Small
    description: Begin your criminal career by establishing connections in the local
      neighborhood.
    order: 1
    missions:
    - id: 62af5e93-cb02-4c06-8335-0a7516e1b0c3
      name: First Connections
      description: Make your first contacts in the criminal underworld.
      order: 1
      prerequisites: []
      branches:
      - id: dc3f7e8a-5291-48d0-a7bd-84e36b8f64e9
        name: The Diplomatic Approach
        description: Build relationships with local business owners through persuasion
          rather than force.
        operations:
        - id: bf61c2d3-95e4-47ab-8a13-6cfd795e027a
          name: Information Gathering
          description: Gather information about local businesses and their owners.
          type: intelligence_gathering
          is_special: true
          regions:
          - 3e0b1d62-f74e-4a9f-9cf9-4a1b9f7b2a4e
          requirements:
            min_influence: 0
            max_heat: 100
            min_title: ''
            required_hotspot_types: ''
          resources:
            crew: 2
            weapons: 0
            vehicles: 1
            money: 500
          rewards:
            money: 1000
            crew: 2
            weapons: 0
            vehicles: 0
            respect: 5
            influence: 3
            heat_reduction: 0
          risks:
            crew_loss: 1
            weapons_loss: 0
            vehicles_loss: 0
            money_loss: 500
            heat_increase: 5
            respect_loss: 2
          duration: 60
          success_rate: 85
        pois:
        - id: e845f17c-d82a-4198-b03e-327a99182541
          name: Café Owner Marco
          description: Owner of a small café that serves as a meeting place for local
            criminals.
          type: bar
          business_type: protection
          is_legal: true
          city_id: a25fec6a-20c8-4ef2-b9c0-2e376e37b0fa
      - id: a7b8c9d0-e1f2-43a4-b5c6-d7e8f9a0b1c2
        name: The Strong-Arm Approach
        description: Take what you want by force and intimidation.
        operations:
        - id: b8c9d0e1-f2a3-44b5-c6d7-e8f9a0b1c2d3
          name: Muscle Recruitment
          description: Recruit local tough guys to form your first crew.
          type: crew_recruitment
          is_special: true
          regions:
          - 5c7d9e1f-3a5b-7c9d-1e3f-5a7b9c1d3e5f
          requirements:
            min_influence: 0
            max_heat: 100
            min_title: ''
            required_hotspot_types: ''
          resources:
            crew: 1
            weapons: 2
            vehicles: 0
            money: 1000
          rewards:
            money: 0
            crew: 5
            weapons: 1
            vehicles: 0
            respect: 10
            influence: 5
            heat_reduction: 0
          risks:
            crew_loss: 1
            weapons_loss: 1
            vehicles_loss: 0
            money_loss: 1000
            heat_increase: 15
            respect_loss: 0
          duration: 60
          success_rate: 75
        pois:
        - id: c9d0e1f2-a3b4-45c6-d7e8-f9a0b1c2d3e4
          name: Boxing Gym Owner Tony
          description: Runs a boxing gym where local tough guys train.
          type: warehouse
          business_type: protection
          is_legal: true
          city_id: d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a
    - id: d6e7f8a9-b0c1-52d3-e4f5-a6b7c8d9e0f1
      name: Territorial Expansion
      description: Expand your influence to neighboring areas.
      order: 2
      prerequisites:
      - 62af5e93-cb02-4c06-8335-0a7516e1b0c3
      branches:
      - id: e7f8a9b0-c1d2-53e4-f5a6-b7c8d9e0f1a2
        name: Strategic Alliances
        description: Form alliances with other small criminal groups to expand your
          influence.
        operations:
        - id: f8a9b0c1-d2e3-54f5-a6b7-c8d9e0f1a2b3
          name: Negotiation Meeting
          description: Arrange a meeting with leaders of local gangs to discuss potential
            alliances.
          type: intelligence_gathering
          is_special: true
          regions:
          - 9d1e3f5a-7b9c-1d3e-5f7a-9b1c3d5e7f9a
          requirements:
            min_influence: 5
            max_heat: 75
            min_title: ''
            required_hotspot_types: ''
          resources:
            crew: 5
            weapons: 3
            vehicles: 1
            money: 2000
          rewards:
            money: 0
            crew: 10
            weapons: 5
            vehicles: 2
            respect: 15
            influence: 10
            heat_reduction: 5
          risks:
            crew_loss: 3
            weapons_loss: 2
            vehicles_loss: 1
            money_loss: 5000
            heat_increase: 10
            respect_loss: 20
          duration: 60
          success_rate: 70
        pois:
        - id: a9b0c1d2-e3f4-55a6-b7c8-d9e0f1a2b3c4
          name: Golden Dragon Restaurant Owner
          description: Owner of a restaurant that serves as a front for a local gang.
          type: restaurant
          business_type: protection
          is_legal: true
          city_id: b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7f
      - id: f4a5b6c7-d8e9-60f1-a2b3-c4d5e6f7a8b9
        name: Hostile Takeover
        description: Eliminate competition and take over their territory by force.
        operations:
        - id: a5b6c7d8-e9f0-61a2-b3c4-d5e6f7a8b9c0
          name: Gang Hideout Raid
          description: Attack a rival gang's hideout to assert dominance in the area.
          type: carjacking
          is_special: true
          regions:
          - 5c7d9e1f-3a5b-7c9d-1e3f-5a7b9c1d3e5f
          requirements:
            min_influence: 5
            max_heat: 100
            min_title: ''
            required_hotspot_types: ''
          resources:
            crew: 10
            weapons: 8
            vehicles: 2
            money: 0
          rewards:
            money: 5000
            crew: 5
            weapons: 10
            vehicles: 3
            respect: 25
            influence: 15
            heat_reduction: 0
          risks:
            crew_loss: 8
            weapons_loss: 5
            vehicles_loss: 2
            money_loss: 0
            heat_increase: 30
            respect_loss: 10
          duration: 60
          success_rate: 60
        pois:
        - id: b6c7d8e9-f0a1-62b3-c4d5-e6f7a8b9c0d1
          name: Harbor Warehouse Guardian
          description: A gang lieutenant who protects their warehouse at the harbor.
          type: warehouse
          business_type: smuggling
          is_legal: false
          city_id: d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a
  - id: a1b2c3d4-e5f6-67a8-b9c0-d1e2f3a4b5c6
    name: Growing Pains
    description: Deal with the challenges of running a growing criminal organization.
    order: 2
    missions:
    - id: b2c3d4e5-f6a7-68b9-c0d1-e2f3a4b5c6d7
      name: Heat Management
      description: Learn to manage heat from law enforcement as your operations become
        more visible.
      order: 1
      prerequisites:
      - d6e7f8a9-b0c1-52d3-e4f5-a6b7c8d9e0f1
      branches:
      - id: c3d4e5f6-a7b8-69c0-d1e2-f3a4b5c6d7e8
        name: Police Corruption
        description: Bribe local police to look the other way.
        operations:
        - id: d4e5f6a7-b8c9-70d1-e2f3-a4b5c6d7e8f9
          name: Officer Recruitment
          description: Identify and approach corrupt police officers who can be bribed.
          type: official_bribing
          is_special: true
          regions:
          - 3e0b1d62-f74e-4a9f-9cf9-4a1b9f7b2a4e
          requirements:
            min_influence: 10
            max_heat: 80
            min_title: Soldier
            required_hotspot_types: ''
          resources:
            crew: 2
            weapons: 0
            vehicles: 1
            money: 10000
          rewards:
            money: 0
            crew: 0
            weapons: 0
            vehicles: 0
            respect: 5
            influence: 10
            heat_reduction: 30
          risks:
            crew_loss: 1
            weapons_loss: 0
            vehicles_loss: 0
            money_loss: 10000
            heat_increase: 50
            respect_loss: 20
          duration: 60
          success_rate: 65
        pois:
        - id: e5f6a7b8-c9d0-71e2-f3a4-b5c6d7e8f9a0
          name: Sergeant Jenkins
          description: A police sergeant known to be open to bribes.
          type: bar
          business_type: protection
          is_legal: true
          city_id: b1c3d5e7-f9a8-4d2e-8c6b-4a2e6f8a0c2e
