# configs/game.yaml

# This file contains the configuration settings for the game.

# Game settings
mechanics_file: "./configs/mechanics.yaml"
territory_structure_file: "./configs/territory.yaml"
operations_file: "./configs/operations.yaml"
daily_operations_count: 10
special_operations_count: 5
# operations_refresh_interval: 1 # in minutes
operations_refresh_interval: 60 # in minutes
market_price_update_interval: 60 # in minutes
resource_limit:
  initial_respect: 10
  initial_influence: 5
  initial_heat: 0
  initial_crew: 500 # Default value: 5
  initial_weapons: 300 # Default value: 3
  initial_vehicles: 1000 # Default value: 1
  initial_money: 10000000 # Default value: 10000
  max_crew: 2500 # Default value: 25
  max_weapons: 3000 # Default value: 30
  max_vehicles: 1200 # Default value: 12
